In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_excel('Indeks Pencemaran Udara.xlsx')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(x)

[['Januari' 'Bunderan HI' 55.0 76.0 27.0 nan 20.0 31.0 76]
 ['Januari' 'Bunderan HI' nan 70.0 33.0 16.0 14.0 30.0 70]
 ['Januari' 'Bunderan HI' 58.0 81.0 33.0 12.0 19.0 25.0 81]
 ['Januari' 'Bunderan HI' 68.0 102.0 27.0 11.0 27.0 22.0 102]
 ['Januari' 'Bunderan HI' 71.0 106.0 28.0 12.0 nan 25.0 106]
 ['Januari' 'Kelapa Gading' 85.0 115.0 53.0 11.0 53.0 19.0 115]
 ['Januari' 'Kelapa Gading' 74.0 99.0 55.0 10.0 58.0 nan 99]
 ['Januari' 'Kelapa Gading' 82.0 114.0 55.0 11.0 58.0 17.0 114]
 ['Januari' 'Kelapa Gading' 74.0 100.0 51.0 10.0 77.0 13.0 100]
 ['Januari' 'Kelapa Gading' 86.0 113.0 51.0 14.0 60.0 19.0 113]
 ['Januari' 'Jagaskara' 64.0 92.0 nan 8.0 22.0 18.0 92]
 ['Januari' 'Jagaskara' 60.0 84.0 47.0 7.0 23.0 18.0 84]
 ['Januari' 'Jagaskara' 80.0 124.0 45.0 10.0 28.0 17.0 124]
 ['Januari' 'Jagaskara' 86.0 132.0 44.0 9.0 28.0 14.0 132]
 ['Januari' 'Jagaskara' 67.0 nan 46.0 nan 38.0 15.0 105]
 ['Februari' 'Bunderan HI' 59.0 79.0 21.0 26.0 15.0 31.0 79]
 ['Februari' 'Bunderan HI' 30.0 

In [4]:
print(y)

['SEDANG' 'SEDANG' 'SEDANG' 'TIDAK SEHAT' 'TIDAK SEHAT' 'TIDAK SEHAT'
 'SEDANG' 'TIDAK SEHAT' 'SEDANG' 'TIDAK SEHAT' 'SEDANG' 'SEDANG'
 'TIDAK SEHAT' 'TIDAK SEHAT' 'TIDAK SEHAT' 'SEDANG' 'BAIK' 'BAIK' 'SEDANG'
 'BAIK' 'BAIK' 'BAIK' 'SEDANG' 'BAIK' 'SEDANG' 'SEDANG' 'BAIK'
 'TIDAK SEHAT' 'BAIK' 'BAIK']


In [5]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 2:9])
x[:, 2:9] = imputer.transform(x[:, 2:9])

In [6]:
print(x)

[['Januari' 'Bunderan HI' 55.0 76.0 27.0 11.62962962962963 20.0 31.0 76.0]
 ['Januari' 'Bunderan HI' 54.714285714285715 70.0 33.0 16.0 14.0 30.0
  70.0]
 ['Januari' 'Bunderan HI' 58.0 81.0 33.0 12.0 19.0 25.0 81.0]
 ['Januari' 'Bunderan HI' 68.0 102.0 27.0 11.0 27.0 22.0 102.0]
 ['Januari' 'Bunderan HI' 71.0 106.0 28.0 12.0 33.25 25.0 106.0]
 ['Januari' 'Kelapa Gading' 85.0 115.0 53.0 11.0 53.0 19.0 115.0]
 ['Januari' 'Kelapa Gading' 74.0 99.0 55.0 10.0 58.0 17.892857142857142
  99.0]
 ['Januari' 'Kelapa Gading' 82.0 114.0 55.0 11.0 58.0 17.0 114.0]
 ['Januari' 'Kelapa Gading' 74.0 100.0 51.0 10.0 77.0 13.0 100.0]
 ['Januari' 'Kelapa Gading' 86.0 113.0 51.0 14.0 60.0 19.0 113.0]
 ['Januari' 'Jagaskara' 64.0 92.0 35.666666666666664 8.0 22.0 18.0 92.0]
 ['Januari' 'Jagaskara' 60.0 84.0 47.0 7.0 23.0 18.0 84.0]
 ['Januari' 'Jagaskara' 80.0 124.0 45.0 10.0 28.0 17.0 124.0]
 ['Januari' 'Jagaskara' 86.0 132.0 44.0 9.0 28.0 14.0 132.0]
 ['Januari' 'Jagaskara' 67.0 77.17857142857143 46.0 11.62

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0,1])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [8]:
print(x)

[[0.0 1.0 1.0 0.0 0.0 55.0 76.0 27.0 11.62962962962963 20.0 31.0 76.0]
 [0.0 1.0 1.0 0.0 0.0 54.714285714285715 70.0 33.0 16.0 14.0 30.0 70.0]
 [0.0 1.0 1.0 0.0 0.0 58.0 81.0 33.0 12.0 19.0 25.0 81.0]
 [0.0 1.0 1.0 0.0 0.0 68.0 102.0 27.0 11.0 27.0 22.0 102.0]
 [0.0 1.0 1.0 0.0 0.0 71.0 106.0 28.0 12.0 33.25 25.0 106.0]
 [0.0 1.0 0.0 0.0 1.0 85.0 115.0 53.0 11.0 53.0 19.0 115.0]
 [0.0 1.0 0.0 0.0 1.0 74.0 99.0 55.0 10.0 58.0 17.892857142857142 99.0]
 [0.0 1.0 0.0 0.0 1.0 82.0 114.0 55.0 11.0 58.0 17.0 114.0]
 [0.0 1.0 0.0 0.0 1.0 74.0 100.0 51.0 10.0 77.0 13.0 100.0]
 [0.0 1.0 0.0 0.0 1.0 86.0 113.0 51.0 14.0 60.0 19.0 113.0]
 [0.0 1.0 0.0 1.0 0.0 64.0 92.0 35.666666666666664 8.0 22.0 18.0 92.0]
 [0.0 1.0 0.0 1.0 0.0 60.0 84.0 47.0 7.0 23.0 18.0 84.0]
 [0.0 1.0 0.0 1.0 0.0 80.0 124.0 45.0 10.0 28.0 17.0 124.0]
 [0.0 1.0 0.0 1.0 0.0 86.0 132.0 44.0 9.0 28.0 14.0 132.0]
 [0.0 1.0 0.0 1.0 0.0 67.0 77.17857142857143 46.0 11.62962962962963 38.0
  15.0 105.0]
 [1.0 0.0 1.0 0.0 0.0 59.0 79.0 

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [10]:
print(y)

[1 1 1 2 2 2 1 2 1 2 1 1 2 2 2 1 0 0 1 0 0 0 1 0 1 1 0 2 0 0]


In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [12]:
print(x_train)

[[1.0 0.0 0.0 1.0 0.0 29.0 42.0 24.0 7.0 30.0 9.0 42.0]
 [0.0 1.0 1.0 0.0 0.0 68.0 102.0 27.0 11.0 27.0 22.0 102.0]
 [1.0 0.0 0.0 0.0 1.0 34.0 53.0 40.0 11.0 42.0 14.0 53.0]
 [1.0 0.0 0.0 0.0 1.0 43.0 62.0 43.0 14.0 33.0 11.0 62.0]
 [1.0 0.0 0.0 0.0 1.0 54.714285714285715 77.17857142857143
  35.666666666666664 8.0 40.0 11.0 47.0]
 [0.0 1.0 1.0 0.0 0.0 71.0 106.0 28.0 12.0 33.25 25.0 106.0]
 [0.0 1.0 1.0 0.0 0.0 58.0 81.0 33.0 12.0 19.0 25.0 81.0]
 [1.0 0.0 0.0 1.0 0.0 45.0 59.0 25.0 13.0 29.0 15.0 59.0]
 [0.0 1.0 0.0 0.0 1.0 74.0 99.0 55.0 10.0 58.0 17.892857142857142 99.0]
 [1.0 0.0 1.0 0.0 0.0 36.0 53.0 23.0 14.0 12.0 24.0 53.0]
 [0.0 1.0 0.0 1.0 0.0 86.0 132.0 44.0 9.0 28.0 14.0 132.0]
 [0.0 1.0 0.0 0.0 1.0 82.0 114.0 55.0 11.0 58.0 17.0 114.0]
 [1.0 0.0 0.0 1.0 0.0 68.0 103.0 26.0 22.0 30.0 14.0 103.0]
 [0.0 1.0 1.0 0.0 0.0 54.714285714285715 70.0 33.0 16.0 14.0 30.0 70.0]
 [1.0 0.0 1.0 0.0 0.0 30.0 46.0 21.0 14.0 33.25 24.0 46.0]
 [0.0 1.0 1.0 0.0 0.0 55.0 76.0 27.0 11.62962962962

In [13]:
print(x_test)

[[1.0 0.0 1.0 0.0 0.0 23.0 33.0 19.0 11.0 14.0 19.0 33.0]
 [1.0 0.0 0.0 0.0 1.0 33.0 49.0 43.0 6.0 35.0 11.0 49.0]
 [0.0 1.0 0.0 1.0 0.0 64.0 92.0 35.666666666666664 8.0 22.0 18.0 92.0]
 [1.0 0.0 1.0 0.0 0.0 29.0 36.0 20.0 14.0 12.0 17.892857142857142 36.0]
 [0.0 1.0 0.0 1.0 0.0 67.0 77.17857142857143 46.0 11.62962962962963 38.0
  15.0 105.0]
 [1.0 0.0 0.0 0.0 1.0 34.0 46.0 39.0 4.0 49.0 10.0 49.0]]


In [14]:
print(y_train)

[0 2 1 1 0 2 1 1 1 1 2 2 2 1 0 1 1 0 0 2 1 2 1 2]


In [15]:
print(y_test)

[0 0 1 0 2 0]


In [16]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 5:] = sc.fit_transform(x_train[:, 5:])
x_test[:, 5:] = sc.transform(x_test[:,5:])

In [17]:
print(x_train)

[[1.0 0.0 0.0 1.0 0.0 -1.4961928622951803 -1.4943412705178365
  -1.0572625339626667 -1.2462853265524492 -0.28057391069144205
  -1.494473274548716 -1.4013648919975314]
 [0.0 1.0 1.0 0.0 0.0 0.5175819186740102 0.7145468046839514
  -0.7959711068048451 -0.2986843977099885 -0.4684931811080359
  0.5337570387117443 0.736310366981754]
 [1.0 0.0 0.0 0.0 1.0 -1.2380166083247712 -1.0893784567308422
  0.3362917442123817 -0.2986843977099885 0.4711031709749333
  -0.714384692525462 -1.0094577611846625]
 [1.0 0.0 0.0 0.0 1.0 -0.7732993511780349 -0.758045245450574
  0.5975831713702033 0.412016298921857 -0.09265464027484821
  -1.1824378417394144 -0.6888064723377696]
 [1.0 0.0 0.0 0.0 1.0 -0.1684292704473623 -0.1992491549977406
  -0.041129206126694066 -1.009385094341834 0.3458236573638708
  -1.1824378417394144 -1.223225287082591]
 [0.0 1.0 1.0 0.0 0.0 0.6724876710562556 0.861806009697404
  -0.7088739644189046 -0.061784165499373336 -0.07699470107346539
  1.0018101879256966 0.8788220509137065]
 [0.0 1.0 1.

In [18]:
print(x_test)

[[1.0 0.0 1.0 0.0 0.0 -1.806004367059671 -1.8256744817981048
  -1.4927482458923693 -0.2986843977099885 -1.2828100195799426
  0.06570388949779195 -1.7220161808444243]
 [1.0 0.0 0.0 0.0 1.0 -1.289651859118853 -1.2366376617442947
  0.5975831713702033 -1.4831855587630645 0.03262487333621436
  -1.1824378417394144 -1.1519694451166147]
 [0.0 1.0 0.0 1.0 0.0 0.311040915497683 0.34639879215032005
  -0.041129206126694066 -1.009385094341834 -0.7816919651356923
  -0.09031382690685884 0.38003115715187313]
 [1.0 0.0 1.0 0.0 0.0 -1.4961928622951803 -1.7152300780380154
  -1.4056511035064287 0.412016298921857 -1.408089533191005
  -0.10703001080735722 -1.61513241789546]
 [0.0 1.0 0.0 1.0 0.0 0.4659466678799284 -0.1992491549977406
  0.858874598528025 -0.14952499224404558 0.2205441437528082
  -0.5583669761208112 0.8431941299307183]
 [1.0 0.0 0.0 0.0 1.0 -1.2380166083247712 -1.347082065504384
  0.2491946018264412 -1.9569860231842946 0.9095814686136523
  -1.3384555581440651 -1.1519694451166147]]
